SUPABASE_URL = "https://lmwczrsbxhavscerebhq.supabase.co"
SUPABASE_KEY = "sb_publishable_Rj1P6kiH_Atg1J5ZegVobA_EHWsp8ig"
OPENAI_API_KEY = "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"
