SUPABASE_URL = "https://lmwczrsbxhavscerebhq.supabase.co"
SUPABASE_KEY = "sb_publishable_Rj1P6kiH_Atg1J5ZegVobA_EHWsp8ig"
OPENAI_API_KEY = "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"
